create table if not exists public.users (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  username varchar null,
  password varchar null,
  is_admin boolean null,
  constraint user_pkey primary key (id)
);

alter table public.users enable row level security;

drop policy if exists "Aucun accès direct users" on public.users;

create policy "Aucun accès direct users"
on public.users
for all
using (false)
with check (false);

create or replace function public.verify_togw_login(
  p_username text,
  p_password text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_username varchar;
  v_password varchar;
  v_is_admin boolean;
begin
  if p_username is null or trim(p_username) = '' or p_password is null then
    return json_build_object('success', false, 'error', 'Identifiants requis');
  end if;

  select u.id, u.username, u.password, u.is_admin
  into v_id, v_username, v_password, v_is_admin
  from public.users u
  where lower(u.username) = lower(trim(p_username))
  limit 1;

  if v_id is null then
    return json_build_object('success', false, 'error', 'Identifiants invalides');
  end if;

  if v_password is distinct from p_password then
    return json_build_object('success', false, 'error', 'Identifiants invalides');
  end if;

  return json_build_object(
    'success', true,
    'user_id', v_id,
    'username', v_username,
    'is_admin', coalesce(v_is_admin, false)
  );
end;
$$;

grant execute on function public.verify_togw_login(text, text) to anon;
grant execute on function public.verify_togw_login(text, text) to authenticated;

notify pgrst, 'reload schema';
